import {
  AccountBox,
  AdminPanelSettings,
  Analytics,
  BarChart,
  Cable,
  Campaign,
  Dashboard,
  Group,
  Hub,
  Notifications,
  People,
  PersonAdd,
  PieChart,
  Polyline,
  Schema,
  Security,
  Segment,
  Settings,
  Timeline,
  TimerOutlined,
} from "@mui/icons-material";
export const menuItems = [
  {
    id: "dashboard",
    title: "Dashboard",
    icon: <Dashboard />,
    path: "/dashboard",
    name: "Dashboard",
  },
  {
    id: "campaigns",
    title: "Campaigns",
    icon: <Campaign />,
    path: "/campaign",
    name: "Campaigns",
  },
  {
    id: "flowboard",
    title: "Flowboard",
    icon: <Cable />,
    path: "/flowboard",
    name: "Flowboard",
  },
  {
    id: "analytics",
    title: "Analytics",
    icon: <Analytics />,
    children: [
      {
        id: "interactions",
        title: "Interaction",
        icon: <BarChart />,
        name: "Analytics / Interaction",
      },
      {
        id: "outcomes",
        title: "Outcomes",
        icon: <BarChart />,
        name: "Analytics / Outcomes",
      },
      {
        id: "pathways",
        title: "Pathways",
        icon: <BarChart />,
        name: "Analytics / Pathways",
      },
      {
        id: "rfm",
        title: "RFM",
        icon: <BarChart />,
        name: "Analytics / RFM",
      },
    ],
  },
  {
    id: "audience",
    title: "Audiences",
    icon: <Segment />,
    children: [
      {
        id: "user-list",
        title: "Explorer",
        icon: <Group />,
        path: "/user",
        name: "Audience / Explorer",
      },
      {
        id: "segments",
        title: "Segment",
        icon: <BarChart />,
        path: "/segment",
        name: "Segment",
      },
    ],
  },
  {
    id: "contentHub",
    title: "Content Hub",
    icon: <Hub />,
    children: [
      {
        id: "library",
        title: "Library",
        icon: <Group />,
        path: "/user",
        name: "Content Hub / Library",
      },
      {
        id: "inAppLayouts",
        title: "Inapp Layouts",
        icon: <BarChart />,
        path: "/app-layout",
        name: "Content Hub / Inapp Layouts",
      },
      {
        id: "emaillayouts",
        title: "Email Layouts",
        icon: <BarChart />,
        path: "/email-layout",
        name: "Content Hub / Email Layouts",
      },
    ],
  },
  {
    id: "timeline",
    title: "Timeline",
    icon: <TimerOutlined />,
    path: "/timeline",
    name: "Timeline",
  },
  {
    id: "schema",
    title: "Schema",
    icon: <Schema />,
    children: [
      {
        id: "events",
        title: "Events",
        icon: <BarChart />,
        name: "Schema / Event",
        path: "/Schema/Events/schema",
      },
      {
        id: "user_properties",
        title: "User Properties",
        icon: <BarChart />,
        name: "Schema / User Properties",
      },
    ],
  },
  // {
  //   id: "users",
  //   title: "User Management",
  //   icon: <People />,
  //   children: [
  //     {
  //       id: "user-list",
  //       title: "Users",
  //       icon: <Group />,
  //       path: "/users",
  //       name: "User Management / Users",
  //     },
  //     // {
  //     //   id: "user-roles",
  //     //   title: "Roles & Permissions",
  //     //   icon: <AdminPanelSettings />,
  //     //   children: [
  //     //     {
  //     //       id: "roles",
  //     //       title: "Roles",
  //     //       path: "/users/roles/list",
  //     //       name: "User Management / Role & Permission / Roles",
  //     //     },
  //     //     {
  //     //       id: "permissions",
  //     //       title: "Permissions",
  //     //       path: "/users/roles/permissions",
  //     //       name: "User Management / Role & Permission / Permissions",
  //     //     },
  //     //     {
  //     //       id: "assignments",
  //     //       title: "Assignments",
  //     //       path: "/users/roles/assignments",
  //     //       name: "User Management / Role & Permission / Assignments",
  //     //     },
  //     //   ],
  //     // },
  //     // {
  //     //   id: "add-user",
  //     //   title: "Add User",
  //     //   icon: <PersonAdd />,
  //     //   path: "/users/add",
  //     //   name: "User Management / Add user",
  //     // },
  //   ],
  // },
  {
    id: "settings",
    title: "Settings",
    icon: <Settings />,
    children: [
      {
        id: "account",
        title: "Account Settings",
        icon: <AccountBox />,
        children: [
          {
            id: "profile",
            title: "Profile",
            path: "/settings/account/profile",
            name: "Setting / Account Setting / Profile",
          },
          {
            id: "preferences",
            title: "Preferences",
            path: "/settings/account/preferences",
            name: "Setting / Account Setting / Preference",
          },
          {
            id: "billing",
            title: "Billing",
            path: "/settings/account/billing",
            name: "Setting / Account Setting / Billing",
          },
        ],
      },
      {
        id: "security",
        title: "Security",
        icon: <Security />,
        children: [
          {
            id: "password",
            title: "Password",
            path: "/settings/security/password",
            name: "Setting / Security / Password",
          },
          {
            id: "two-factor",
            title: "Two-Factor Auth",
            path: "/settings/security/2fa",
            name: "Setting / Security / Two-Factor Auth",
          },
          {
            id: "sessions",
            title: "Active Sessions",
            path: "/settings/security/sessions",
            name: "Setting / Security / Sessions",
          },
        ],
      },
      {
        id: "system",
        title: "System",
        icon: <Notifications />,
        children: [
          {
            id: "backups",
            title: "Backups",
            path: "/settings/system/backups",
            name: "Setting / System / Backups",
          },
          {
            id: "updates",
            title: "Updates",
            path: "/settings/system/updates",
            name: "Setting / System / Updates",
          },
          {
            id: "logs",
            title: "Logs",
            path: "/settings/system/logs",
            name: "Setting / System / Logs",
          },
        ],
      },
    ],
  },
];
