const usersList = [
  {
    name: "John Doe",
    role: "Admin",
    email: "john@example.com",
    status: "ACTIVE",
    lastAccessed: "Sep 01, 2022, 00:00 AM",
    passcodeStatus: "Inactive",
  },
  {
    name: "Jane Smith",
    role: "Admin",
    email: "jane@example.com",
    status: "ACTIVE",
    lastAccessed: "Aug 23, 2023, 03:28 PM",
    passcodeStatus: "Inactive",
  },
  {
    name: "Alice Johnson",
    role: "Admin",
    email: "alice@example.com",
    status: "ACTIVE",
    lastAccessed: "Sep 01, 2022, 00:00 AM",
    passcodeStatus: "Inactive",
  },
  {
    name: "Bob Thomas",
    role: "Admin",
    email: "bob@example.com",
    status: "ACTIVE",
    lastAccessed: "Jun 28, 2023, 02:04 AM",
    passcodeStatus: "Inactive",
  },
  {
    name: "Charlie Brown",
    role: "Admin",
    email: "charlie@example.com",
    status: "INVITED",
    lastAccessed: "Never Logged In",
    passcodeStatus: "Inactive",
  },
  {
    name: "Eve Watson",
    role: "Admin",
    email: "eve@example.com",
    status: "ACTIVE",
    lastAccessed: "Aug 24, 2023, 01:36 PM",
    passcodeStatus: "Inactive",
  },
  {
    name: "Mike Lee",
    role: "Admin",
    email: "mike@example.com",
    status: "ACTIVE",
    lastAccessed: "Sep 01, 2022, 00:00 AM",
    passcodeStatus: "Inactive",
  },
];
